from named_constants import Constants


class Const(Constants):
    DB_HOST = 'external-db.s4086.gridserver.com'
    DB_NAME = 'db4086_modd'
    DB_USER = 'db4086_modd_usr'
    DB_PASS = 'f4zeHUga.age'

    VERIFY_TOKEN = "d41d8cd98f00b204e9800998ecf8427e"
    HAPPYHOUR_ACCESS_TOKEN = "EAADo7UONMbQBAG7fZBXMO5TYmZBHpKGgEzrIWG0LuAScIRbVQhgtN2Q4nJiMKCnvZBP9TRkhiaexEXfTpJXhlMpkl0ZBsnJm4lVu3qXZB69b7WzmNsHhpZCmcKTnKwCLS1jJGsUvqnGHW7x743T2LOTnFjFfXhZC2HyMl1P0vMxEgZDZD"
    TOPSTYLE_ACCESS_TOKEN = "EAAJsLJoIWPUBAFzJszKHQHGKgrzpS1MZA0bD8h9bRsYGQcKMqdzkdcHwZBkxrgvJwp7sRV1R2fUUOcZBlNDTHSz8bHQNSDhZCWKGnflj5CIeiZAPnZA4CkAVFGfhFknfCwilwDRWGArpLZBYK5FuiRWOvAGJlEhoAKCgkaeGNUA5AZDZD"

    RESERVED_MENU_REPLIES = "menu"
    RESERVED_ALERT_REPLIES = "alert"
    RESERVED_OPTOUT_REPLIES = "optout|quit|exit"


