from named_constants import Constants

class Const(Constants):

    DB_HOST = 'external-db.s4086.gridserver.com'
    DB_NAME = 'db4086_modd'
    DB_USER = 'db4086_modd_usr'
    DB_PASS = 'f4zeHUga.age'

    VERIFY_TOKEN = "d41d8cd98f00b204e9800998ecf8427e"
    GAMEBOTS_ACCESS_TOKEN = "EAAXFDiMELKsBAESoNb9hvGcOarJZCSuHJOQCjC835GS1QwwlOn8D255xPF86We1Wxg4DtxQqr91aHFYjFoOybUOVBTdtDalFKNLcjA2EXTEIGHXEMRbsA4vghEWKiIpB6nbzsX6G5rYBZCHuBc1UlsUnOqwZAS2jY56xppiIgZDZD"
    GAMEBAE_ACCESS_TOKEN = "EAAMEWAWmjzoBADaIJqV7ZC4ou9PoozUX2UUoNw76lg1JQELd4HJkZB3BMmcRLBKXEHIK47vfpRcqf1dkzxoYGHDkXBQ8O2oCXSB146NLiFlrhCcXh3t5e19GOllOXlZCZC3wgw7mqYDCMbB7QqbfZAok6z8mxJoZAT7CXJD5TkhAZDZD"
    H1Z1_ACCESS_TOKEN = "EAAB2t2cZAybcBAPbJVUaorFzAovXRLVEkZBPNkp1tqwQYeyFpDtHRJaqd4qVXSVylH36nVHpF1UPPEMVEb8XvXzmZCV9SyTvEicdNrWfoQ6ZAF6QghVhvv86jAZCGxtiZBCvXJ2zrsYZB44hpQ47P1BXRZAfZAbeljwTtSVXiLSV2pwZDZD"
    DOTA2_ACCESS_TOKEN = "EAAYsMw6RCCMBAN73x4vfOOKNPLjHltWN3rZAMcsjfTZAHZCdCekfoZBVyvqf29wYWZCIhoZAmnMQu7ZCLKUonbURE2jdilRtBtAK4Pp5q2PPhxvobjSACfUJWYulw5bhf1MCvgcFPxE9VE9PCtIF4iaDg32XMN5fX6ZATsOxjoEeZBgZDZD"
    CSGOSPICE_ACCESS_TOKEN = "EAALm6t1uPKIBALoE7ZCT5ZBBCz5kP7yNBToTKIZCbZAIYvtZBi88VHBuvgD6C2ZBaxQdTBJfYYXPerW4LF5IGFKIHZAGxDTXjDUIQCGqdZAKMDM5zzLCKh9uKGSKZCvAfisSCZC2i4hZBynxXrL8FRZBAOadZBe0N9AMMWYy1fCz6qhrkuAZDZD"
    CSGOBUNNY_ACCESS_TOKEN = "EAAKRJY6Jjs4BAFRYEbROL1tdwQ1OOTooSJVd0YURdh9IooDuZAKrS1XqVeWIrAq1iON7Pn2MRlJpKeM1JDCocYEMQlPaQMiKFdVsSK0W3RhKopNdZA7KqA78mbrjhetXw3nhGnmbsqEoqq4ou7x2Ubvj59px8hIirfALiZBOQZDZD"
    CSGOBURRITO_ACCESS_TOKEN = "EAAaYjvJJXucBAAKd1DEcnZBK3qV3ZCIX87r7FwpKqdUkOWAUcamH7zn3ZBvZB3Jxu5F11aQFZCKEi4Igc2wrAUZBE0l1gRRViybkZAl82v2zJzBZAJ09FmRFNpnVkKfajUHt0oF4lr6ak9ftaHUt3VRaRGY7ttu6DQPAmYYS0mdG6gZDZD"
    CSGOPIZZA_ACCESS_TOKEN = "EAAcWVl9p3GABABdVGiViKKgCKxFlmGVrFDTtB7HUfe1cvxwcZAyhOTuLcVM6K20rWYznUvsNUO9nJLQrOvXKGswQVKi70ZBmFuON4WQhXzgsZAZC5srJY1iOFdfYSW9hQ3wrZB6MAgBjVT1QvcsqFVc8zQ7GEzneZAOUATXZCmq4gZDZD"
    CSGOSUSHI_ACCESS_TOKEN = "EAAaxinx0K6oBAHdTZAZCxjQWD45Kx1J3l05nqbLXyqt5RnEpEvLqZC2nygxFqZBkGS8qZCkJTzz102ABMWOBZBkPAUsIAk2s5OwZAU00AwHOtu0suZAwGpz6dZBnH1ZAqf2SNaWZAzZCB0KuLxfZBnBC9NgxLtu4TOwAfWjAR788ZCWtF9ngZDZD"
    CSGOSTONER_ACCESS_TOKEN = "EAAZAmQpmLVVkBANQA9wAzvPXF9N6qBgkWFrdCtb0Xwt4sHwFFaZARuDoasPwhX7o6fkgGAvl3xHQcVMvZAp5LuZCJP0nP0sQKtbddvssyi5CAmsr7ptJP43X9fBQGxMn41ZCudzpFA6XzicFYN9Pz1NVsuDR7uBcXCwWQHZCpOtAZDZD"
    CSGOBLAZE_ACCESS_TOKEN = "EAAJWiZCz0JQkBAGLFJhzwDBOOuWlErbhDKKxrg4LVWUaTpySLNK2NtAceLRuqZBmO1ZCGi1hJ1mPZAZCesqTiwMSKIHcl7lGH9wsbyNE2CiSmZBVsCNqI0UOEK5g94uBPWE5FyhWcGoSHingaCGfIsAqLjgdPcad2nQAA1eVOz6QZDZD"

    SLACK_TOKEN = "6RXsSkHyeISqgHG7aYGk7S94"

    PAYPAL_TOKEN = "882499ef6be6c2575a7a8b2be032e42f"
    BONUS_TOKEN = "476b5353b4ea9a12e778ea445d0a4043"
    POINTS_TOKEN = "457a7fa6c8319c5e6c2fcc990b423981"

    BOT_TYPE_GAMEBOTS = 1
    BOT_TYPE_GAMEBAE = 2
    BOT_TYPE_H1Z1 = 3
    BOT_TYPE_DOTA2 = 4
    BOT_TYPE_CSGOSPICE = 5
    BOT_TYPE_CSGOBUNNY = 6
    BOT_TYPE_CSGOBURRITO = 7
    BOT_TYPE_CSGOPIZZA = 8
    BOT_TYPE_CSGOSUSHI = 9
    BOT_TYPE_CSGOSTONER = 10
    BOT_TYPE_CSGOBLAZE = 11


    #-- toofus|jason|charles|bryan|kelvin
    ADMIN_FB_PSID = "1298454546880273|894483894011953|1273333236086624|1051754691601951|1890115771013966"

    # TEST_PAYMENTS = 1
    TEST_PAYMENTS = 0

    # FLIP_CLAIM_URL = "www.gamebots.chat/giveaway.html"
    FLIP_CLAIM_URL = "taps.io/gamebotsc"

    TRADE_URL_PURCHASE = "TRADE_URL_PURCHASE"
    TRADE_URL_FLIP_ITEM = "TRADE_URL_FLIP_ITEM"

    FLIP_COIN_START_GIF_URL = "http://i.imgur.com/C6Pgtf4.gif"
    FLIP_COIN_WIN_GIF_URL = "http://i.imgur.com/9fmZntz.gif"
    FLIP_COIN_LOSE_GIF_URL = "http://i.imgur.com/7YNujdq.gif"
    SHARE_IMAGE_URL = "https://pbs.twimg.com/profile_images/840610720563642368/p5TfHdUP_400x400.jpg"

    GA_TRACKING_ID = "UA-79705534-3"
    GA_TRACKING_URL = "http://www.google-analytics.com/collect"

    MAX_TIER_WINS = 2
    MAX_LOSSING_STREAK = 12
    MAX_FLIPS_PER_DAY = 100

    SESSION_STATE_UNKNOWN                 = -1
    SESSION_STATE_NEW_USER                = 0
    SESSION_STATE_HOME                    = 1
    SESSION_STATE_FLIPPING                = 2
    SESSION_STATE_FLIP_TRADE_URL          = 3
    SESSION_STATE_FLIP_LMON8_URL          = 4
    SESSION_STATE_SUPPORT                 = 5

    SESSION_STATE_PURCHASED_ITEM          = 10
    SESSION_STATE_PURCHASED_TRADE_URL     = 11

    PAYLOAD_TYPE_QUICK_REPLY = "PAYLOAD_TYPE_QUICK_REPLY"
    PAYLOAD_TYPE_POSTBACK = "PAYLOAD_TYPE_POSTBACK"
    PAYLOAD_TYPE_ATTACHMENT = "PAYLOAD_TYPE_ATTACHMENT"
    PAYLOAD_TYPE_OTHER = "PAYLOAD_TYPE_OTHER"


    PAYLOAD_ATTACHMENT_TEXT = "PAYLOAD_ATTACHMENT-text"
    PAYLOAD_ATTACHMENT_IMAGE = "PAYLOAD_ATTACHMENT-image"
    PAYLOAD_ATTACHMENT_VIDEO = "PAYLOAD_ATTACHMENT-video"
    PAYLOAD_ATTACHMENT_URL = "PAYLOAD_ATTACHMENT-url"
    PAYLOAD_ATTACHMENT_FALLBACK = "PAYLOAD_ATTACHMENT-fallback"
    PAYLOAD_ATTACHMENT_OTHER = "PAYLOAD_ATTACHMENT-OTHER"

    APPNEXT_REPLIES = "f1xgb"
    MODERATOR_REPLIES = "mod"
    MAIN_MENU_REPLIES = "menu|main menu|menu|mainmenu|home"
    TRADE_STATUS_REPLIES = "trades"
    SUPPORT_REPLIES = "support|help"
    FAQ_REPLIES = "faq"
    UPLOAD_REPLIES = "upload"
    GIVEAWAY_REPLIES = "giveaway|snap|twitter|ig|twitch|yt"
    OPT_OUT_REPLIES = "optout|quit|end|stop|exit"
    FBPSID_REPLIES = "id"
    TASK_REPLIES = "tasks"

    BANNED_USERS = ""
